apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-images-ebornet-com
  name: go-images-ebornet-com
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-images-ebornet-com
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-images-ebornet-com
    spec:
      containers:
      - env:
        - name: YRONWOOD_AUTHENTICATION_BASIC_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: go-images-ebornet-com
        - name: YRONWOOD_AUTHENTICATION_BASIC_SALT
          valueFrom:
            secretKeyRef:
              key: salt
              name: go-images-ebornet-com
        - name: YRONWOOD_AUTHENTICATION_SIGHNING_KEY
          valueFrom:
            secretKeyRef:
              key: signingkey
              name: go-images-ebornet-com
        image: 172.16.16.2:2443/go:yronwood-fd865fb
        imagePullPolicy: IfNotPresent
        name: yronwood
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 1536Mi
          requests:
            cpu: 400m
            memory: 768Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /images
          name: images-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: images-volume
        persistentVolumeClaim:
          claimName: glusterfs-images-claim