apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-images-ebornet-com
  labels:
    app: go-images-ebornet-com
spec:
  selector:
    matchLabels:
      app: go-images-ebornet-com
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-images-ebornet-com
    spec:
      containers:
        - name: yronwood
          image: 172.16.32.2:2443/go:yronwood-6889d75
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 768Mi
          volumeMounts:
          - name: images-volume
            mountPath: /images
            readOnly: false
          env:
          - name: YRONWOOD_AUTHENTICATION_BASIC_SECRET
            valueFrom:
              secretKeyRef:
                name: go-images-ebornet-com
                key: secret
          - name: YRONWOOD_AUTHENTICATION_BASIC_SALT
            valueFrom:
              secretKeyRef:
                name: go-images-ebornet-com
                key: salt
      volumes:
      - name: images-volume
        persistentVolumeClaim:
          claimName: glusterfs-images-claim
---
apiVersion: v1
kind: Service
metadata:
  name: go-images-ebornet-com
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-images-ebornet-com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-images-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 50Gi