apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-images-chongya-ng
  labels:
    app: web-images-chongya-ng
spec:
  selector:
    matchLabels:
      app: web-images-chongya-ng
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-images-chongya-ng
    spec:
      containers:
        - name: yronwood
          image: icydoge/web:web-images-chongya-ng-fd865fb
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-images-chongya-ng
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-images-chongya-ng